environment:
  app_name: MoniTalks Social
  base_route_domain: ""
  db_type: mongo
  debug: "true"
  header_cookie_name: he
  org_avatar: https://avatars3.githubusercontent.com/u/43268620
  org_name: Moni Talks
  payload_cookie_name: pa
  phone_source_number: "0123456"
  read_timeout: 10s
  recaptcha_site_key: 6LdEFdMaAAAAACw4knRdxqF0ZJzc6NfmtDad36gM
  redis_address: redis.default.svc.cluster.local:6379
  ref_email: project.scapa@gmail.com
  signature_cookie_name: si
  smtp_email: smtp.gmail.com:587
  write_timeout: 10s
