environment:
  cookie_root_domain: .social.monitalks.io
  internal_gateway: http://openfaas.default.svc.cluster.local:8080/function
  websocket_server_url: https://ws.social.monitalks.io
  gateway: https://social.monitalks.io
  origin: "https://openfaas.social.monitalks.io,https://social.monitalks.io,https://auth.social.monitalks.io"
